services:
  piper-tts:
    container_name: piper-tts
    build: .
    restart: unless-stopped
    ports:
      - "5100:5000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Berlin
